version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      args:
        PROJECT_NAME: MiProyecto
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 4200:4200
    environment:
      - NODE_ENV=development
      # - PROJECT_NAME=MiProyecto